# Escape from the maze by moving to the X mark.
# Try to collect as many coins as you can.
hero.moveRight()
hero.attack("Gate")
hero.moveUp(2)
hero.moveDown(2)
hero.moveLeft()
hero.attack("Treasure Chest")
hero.moveUp()
hero.moveDown()
hero.moveLeft(2)
hero.moveUp(2)
hero.moveLeft()
hero.attack("Ursa")
hero.moveLeft()
hero.moveRight(2)
hero.moveDown()
hero.moveRight()
hero.moveUp()
hero.moveRight()
hero.moveUp(2)
hero.moveLeft()
hero.attack("Inski")
hero.moveLeft()
hero.moveRight(2)
hero.moveDown()
hero.moveRight()
hero.moveUp()
hero.moveRight()
hero.moveUp(2)
hero.attack("Shema")
hero.moveLeft(2)
hero.moveRight(2)
hero.moveDown()
hero.moveRight()
hero.moveUp()
hero.moveRight()